config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'paginas#home'
  get '/sobre', to: 'paginas#sobre'
  get '/produtos', to: 'produtos#produtos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def home
  end

  def sobre
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def produtos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/_footer.html.erb
<div id="wrapper">
    <div id="container">
      <p>Inventos Digitais - Desafio Rafael Guzmán</p>
    </div>
</div>
<div id="footer"></div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-gift"></i> Toys'R'Them
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" 
                                 data-target="#navbarSupportedContent"
                                 aria-controls="navbarSupportedContent"
                                 aria-expanded="false" 
                                 aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <span class="navbar-text">
          <strong><i class="fas fa-user-astronaut"></i> <%= current_user.email %></strong>
        </span>
        <li class="nav-item">
            <%= link_to 'Minha Conta', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "nav-link" %>       
        </li>
      <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sobre', sobre_path, class: "nav-link" %>
          </li>
      <% end %>   
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>ID-Desafio</title>    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

  
  

app/views/paginas/home.html.erb
<div class="jumbotron">
  <h1><i class="fas fa-gift"></i> Seja bem-vindo!</h1>
  <p>Seus capangas favoritos estão lhe esperando...</p> 
  <%= link_to 'Cadastre-se', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
</div>

app/views/paginas/sobre.html.erb
<h1>Sobre nós</h1>
<p> Esta aplicação é um desafio e ainda está em construção!</p>

app/views/produtos/produtos.html.erb
<div class="container-fluid">
  <h1>Produtos</h1>
  <p>Mussum Ipsum, cacilds vidis litro abertis. Manduma pindureta quium dia nois paga. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. </p>
  <p>Quem num gosta di mim que vai caçá sua turmis! Casamentiss faiz malandris se pirulitá.</p>
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover text-center">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Produto</th>
          <th scope="col">Descrição</th>
          <th scope="col">Quantidade</th>
          <th scope="col">Reservar</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Produto 1</td>
          <td>Excelente produto1</td>
          <td>
            <select class="custom-select col-md-3">
              <option selected>1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="3">4</option>
              <option value="3">5</option>
            </select>
          </td>
          <td class="text-center">
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
            </div>  
          </td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Produto 2</td>
          <td>Excelente produto2</td>
          <td>
            <select class="custom-select col-md-3">
              <option selected>1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="3">4</option>
              <option value="3">5</option>
            </select>
          </td>
          <td class="text-center">
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
            </div>  
          </td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Produto 3</td>
          <td>Excelente produto3</td>
          <td>
            <select class="custom-select col-md-3">
              <option selected>1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="3">4</option>
              <option value="3">5</option>
            </select>
          </td>
          <td class="text-center">
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
            </div>  
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <footer class="row">
        <div class="col-sm-6">
          <button class="btn btn-primary" name="botao-novaReserva" data-toggle="modal" data-target="#NovaReserva">Fazer reserva</button>
        </div>
  </footer>
</div>